### ISSUE TITLE
knapsack-pro-jest not respecting "testFailureExitCode" Jest configuration option

### ISSUE THREAD

**Issue by ImOnMars** [KnapsackPro/knapsack-pro-jest#43]
I'm not sure why this is happening, it works locally with the same CLI options and config:

```javascript
// jest-ci.config.js

const mainConfig = require('./jest.config');

module.exports = {
  ...mainConfig,
  testFailureExitCode: 0,
};
```

```bash
# executed locally in bash

> cross-env NODE_ENV=test NODE_ICU_DATA=node_modules/full-icu jest --passWithNoTests --config=jest-ci.config.js
# test failures occur
> echo $?
0
```
which works, if I just use the default config the exit code is 1 as expected.

but then I use it in my CI workflow with Knapsack:
```yaml
# executed in GitHub Actions CI workflow

      - name: Run Jest
        env:
          NODE_ENV: test
          KNAPSACK_PRO_TEST_SUITE_TOKEN_JEST: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_JEST }}
          KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true
          KNAPSACK_PRO_TEST_FILE_PATTERN: "app/**/*test.js"
        run: |
          npm ci
          $(npm bin)/knapsack-pro-jest --ci --runInBand --passWithNoTests --config=jest-ci.config.js
```
and the step exits after successfully running all tests (no configuration/load errors, only test failures) with the following message:
```
Error: Process completed with exit code 1.
```
